[package]
name = "asb-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
asb-core = { version = "=0.1.0", path = "../asb-core" }
rustix = { version = "=1.1.4", features = ["process"] }
sha2 = "=0.11.0"

[dev-dependencies]
asb-replay = { version = "=0.1.0", path = "../asb-replay" }
serde_json = "=1.0.143"

[lints]
workspace = true
